In [1]:
import numpy as np
from scipy.linalg import svd

import matplotlib.pyplot as plt

$$A = U \,\Sigma \,V^T$$
$$A^T A = V \, (\Sigma^T\, \Sigma) V^T$$
$$U = AV\Sigma^{-1}$$

In [2]:
A = np.array([[1, 3, 5], [3, 5, -7], [8, 9, 2]] )
X = np.matmul(A.T, A)

In [3]:
evals, right_evecs = np.linalg.eig(X)

Sigma = np.zeros((3,3))
for i in range(3):
    Sigma[i,i] = np.sqrt(evals[i])
    
left_vecs = np.matmul(np.matmul(A, right_evecs), np.linalg.inv(Sigma))

In [4]:
left_vecs, right_evecs, Sigma

(array([[ 0.21192652,  0.79469621,  0.56881024],
        [ 0.43014928,  0.44676913, -0.78445455],
        [ 0.87752991, -0.41092004,  0.24715578]]),
 array([[ 6.23522619e-01, -7.81500799e-01,  2.18184363e-02],
        [ 7.81673321e-01,  6.23687326e-01,  9.69238228e-04],
        [-1.43653426e-02,  1.64505476e-02,  9.99761480e-01]]),
 array([[13.66849155,  0.        ,  0.        ],
        [ 0.        ,  1.47454323,  0.        ],
        [ 0.        ,  0.        ,  8.83165109]]))

In [11]:
svd(A)

(array([[-0.21192652, -0.56881024,  0.79469621],
        [-0.43014928,  0.78445455,  0.44676913],
        [-0.87752991, -0.24715578, -0.41092004]]),
 array([13.66849155,  8.83165109,  1.47454323]),
 array([[-6.23522619e-01, -7.81673321e-01,  1.43653426e-02],
        [-2.18184363e-02, -9.69238228e-04, -9.99761480e-01],
        [-7.81500799e-01,  6.23687326e-01,  1.64505476e-02]]))